name: async_overlay
description: "AsyncOverlay is a simple package for creating custom loading overlays during async Future operations, inspired by FutureProgressDialog."
version: 1.0.0
repository: https://github.com/imark00/async_overlay
issue_tracker: https://github.com/imark00/async_overlay/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


